apiVersion: v1
kind: ConfigMap
metadata:
  name: video-configmap
data:
  MYSQL_DATABASE: videos_db
  MYSQL_USER: videouser
---
apiVersion: v1
kind: Secret
metadata:
  name: video-secret
type: Opaque
data:
  MYSQL_PASSWORD: Password
  MYSQL_ROOT_PASSWORD: Password
