version: "1"

services:
  auth: 
    build: ./Authentication
    ports: 
      - "3000:3000"
    networks:
      - a1_network

  upload:
    build: ./Upload
    ports:
      - "3060:3060"
    networks:
      - a1_network
    # volumes:
    #   - videos_fs:/app/uploads

  stream:
    build: ./Stream
    ports: 
      - "3030:3030"
    networks:
      - a1_network
    volumes:
      - videos_fs:/app/uploads

  filesystem:
    build: ./Filesystem
    ports:
      - "3090:3090"
    networks:
      - a1_network
    volumes:
      - videos_fs:/app/uploads

  db:
    build: ./MySQL
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - videos_db:/var/lib/mysql
    networks:
      - a1_network
  db-init:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: "mysql --user=root --password=Password videos_db < /tmp/schema.sql"
    volumes:
      - /MySQL/schema.sql:/tmp/schema.sql

volumes:
  videos_db:
    driver: local
  videos_fs:
    driver: local

networks:
  a1_network:
    external: true
    name: a1_network