# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name: "3306"
      protocol: TCP
      port: 3306
      targetPort: 3306
---
# Authentication Service
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication ### auth originally
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
# Filesystem
apiVersion: v1
kind: Service
metadata:
  name: filesystem-service
spec:
  selector:
    app: filesystem
  ports:
    - protocol: TCP
      port: 3090
      targetPort: 3090
  type: LoadBalancer
---
# Upload
apiVersion: v1
kind: Service
metadata:
  name: upload-service
spec:
  selector:
    app: upload
  ports:
    - protocol: TCP
      port: 3060
      targetPort: 3060
  type: LoadBalancer
---
# Stream
apiVersion: v1
kind: Service
metadata:
  name: stream-service
spec:
  selector:
    app: stream
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
  type: LoadBalancer
